version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortened_url_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phoenix:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@db/shortened_url_dev
    ports:
      - "4000:4000"
    command: >
      sh -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"

volumes:
  postgres_data:
